<?php //SNSシェア設定をデータベースに保存

//シェアボタンの表示
update_theme_option(OP_SNS_TOP_SHARE_BUTTONS_VISIBLE);
//SNSシェアメッセージ
update_theme_option(OP_SNS_TOP_SHARE_MESSAGE);
//Twitterシェアボタンの表示
update_theme_option(OP_TOP_TWITTER_SHARE_BUTTON_VISIBLE);
//Facebookシェアボタンの表示
update_theme_option(OP_TOP_BOTTOM_FACEBOOK_SHARE_BUTTON_VISIBLE);
//はてなブックマークシェアボタンの表示
update_theme_option(OP_TOP_BOTTOM_HATEBU_SHARE_BUTTON_VISIBLE);
//Google+シェアボタンの表示
update_theme_option(OP_TOP_BOTTOM_GOOGLE_PLUS_SHARE_BUTTON_VISIBLE);
//Pocketシェアボタンの表示
update_theme_option(OP_TOP_BOTTOM_POCKET_SHARE_BUTTON_VISIBLE);
//LINE@シェアボタンの表示
update_theme_option(OP_TOP_BOTTOM_LINE_AT_SHARE_BUTTON_VISIBLE);
//SNSシェアボタンカラー
update_theme_option(OP_SNS_TOP_SHARE_BUTTON_COLOR);
//シェアボタンのカラム数
update_theme_option(OP_SNS_TOP_SHARE_COLUMN_COUNT);
//SNSシェアボタンのロゴとキャプションの位置
update_theme_option(OP_SNS_TOP_SHARE_LOGO_CAPTION_POSITION);
//SNSトップシェア数の表示
update_theme_option(OP_SNS_TOP_SHARE_BUTTONS_COUNT_VISIBLE);